include(CMakeForceCompiler)

macro(CMAKE_FORCE_ASM_COMPILER compiler id)
  set(CMAKE_ASM_COMPILER "${compiler}")
  set(CMAKE_ASM_COMPILER_ID_RUN TRUE)
  set(CMAKE_ASM_COMPILER_ID ${id})
  set(CMAKE_ASM_COMPILER_FORCED TRUE)

  # Set old compiler id variables.
  if("${CMAKE_ASM_COMPILER_ID}" MATCHES "GNU")
    set(CMAKE_COMPILER_IS_GNUASM 1)
  endif()
endmacro()


macro(FORCE_TOOLCHAIN TOOLCHAIN_PATH TARGET)
    CMAKE_FORCE_C_COMPILER("${TOOLCHAIN_PATH}/bin/${TARGET}-gcc${CMAKE_EXECUTABLE_SUFFIX}" GNU)
    CMAKE_FORCE_CXX_COMPILER("${TOOLCHAIN_PATH}/bin/${TARGET}-g++${CMAKE_EXECUTABLE_SUFFIX}" GNU)
    CMAKE_FORCE_ASM_COMPILER("${TOOLCHAIN_PATH}/bin/${TARGET}-gcc${CMAKE_EXECUTABLE_SUFFIX}" GNU)

    set(CMAKE_AR           "${TOOLCHAIN_PATH}/bin/${TARGET}-ar${CMAKE_EXECUTABLE_SUFFIX}"      CACHE PATH "archive" )
    set(CMAKE_LINKER       "${TOOLCHAIN_PATH}/bin/${TARGET}-ld${CMAKE_EXECUTABLE_SUFFIX}"      CACHE PATH "linker" )
    set(CMAKE_NM           "${TOOLCHAIN_PATH}/bin/${TARGET}-nm${CMAKE_EXECUTABLE_SUFFIX}"      CACHE PATH "nm" )
    set(CMAKE_OBJCOPY      "${TOOLCHAIN_PATH}/bin/${TARGET}-objcopy${CMAKE_EXECUTABLE_SUFFIX}" CACHE PATH "objcopy" )
    set(CMAKE_OBJDUMP      "${TOOLCHAIN_PATH}/bin/${TARGET}-objdump${CMAKE_EXECUTABLE_SUFFIX}" CACHE PATH "objdump" )
    set(CMAKE_RANLIB       "${TOOLCHAIN_PATH}/bin/${TARGET}-ranlib${CMAKE_EXECUTABLE_SUFFIX}"  CACHE PATH "ranlib" )
    set(CMAKE_STRIP        "${TOOLCHAIN_PATH}/bin/${TARGET}-strip${CMAKE_EXECUTABLE_SUFFIX}"   CACHE PATH "strip" )
endmacro()

set(CMAKE_SYSTEM_NAME ChrisOS)
set(TARGET_ARCH i686-pc-elf)

set(ARCH_C_FLAGS "-std=gnu99 -nostdlib -ffreestanding -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-3dnow -I${PROJECT_SOURCE_DIR}/kernel/ia32")

#CMAKE_FORCE_ASM_COMPILER(${TARGET_ARCH}-as GNU)
#CMAKE_FORCE_C_COMPILER(${TARGET_ARCH}-gcc GNU)
#CMAKE_FORCE_CXX_COMPILER(${TARGET_ARCH}-g++ GNU)
#SET(CMAKE_C_LINK_EXECUTABLE ${TARGET_ARCH}-ld)
#SET(CMAKE_CXX_LINK_EXECUTABLE ${TARGET_ARCH}-ld)

SET(CMAKE_FIND_ROOT_PATH /usr/local/cross/ia32)
FORCE_TOOLCHAIN(/usr/local/cross/ia32 ${TARGET_ARCH})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

